### ISSUE TITLE
shorkcut and close icon

### ISSUE THREAD

**Issue by vacuityv** [HamedMP/SuperTabs#4] opened 2018-02-06 08:04 UTC
As a user i want to open id quickly so i want to open it with my keyboard, ans I think shortcut is nice.
Also I opened 50 tabs and cant see clearly so it's difficult to close some of them. So maybe you guys can add a icon behind each of the list so i can just click to close it. Like your ex and best wished to you.

**Comment by HamedMP** [comment] 2018-05-29 08:45
Duplicate of #3

**Closed by HamedMP** 2018-05-29 08:45 UTC
